### ISSUE TITLE
RSS uses incorrect date format

### ISSUE THREAD

**Issue by paulsnar** [Hirrolot/hirrolot.github.io#2]
First of all, I really appreciate you having an RSS feed on your blog even without using any of the pre-made platforms or tools for doing so.

Unfortunately, when I tried adding it to my feed reader, the dates are all wrong, mostly because they're in a freeform format, but as per the [spec,](https://cyber.harvard.edu/rss/rss.html#ltpubdategtSubelementOfLtitemgt) they should be RFC 822 conformant.

I'd love to have filed a pull request to fix this if it were a code issue, but I couldn't find any pertinent code, and it doesn't appear any of this repository has a license attached so it'd be a bit of a grey area.

Cheers!

**Comment by paulsnar** [comment]
Also relatedly, it's a good practice to add a \<guid> along with the \<link> (same value can be shared for both—or, I believe, you can omit the \<link> if the \<guid> doesn't have a `isPermaLink="false"` and it'll work the same in most cases) so that feed readers can more easily tell whether an \<item> has been seen before; the fuzzy algorithms they try to apply if there's no \<guid> can get funky sometimes.

Side note, this is in part why I am impartial to Atom over RSS, given that it's [more concrete and less freeform](https://tools.ietf.org/html/rfc4287) and therefore easier to consume programmatically, but it can cut both ways depending on the content. There are more fancities such as [JSON Feed](https://jsonfeed.org/) too, but that's probably too esoteric.

**Comment by Hirrolot** [comment]
I'm sorry for that, I'm quite new to all this blog posting stuff.

I've fixed `<pubDate>` and placed `<guid>` instead of `<link>`. Is it working now?

**Comment by paulsnar** [comment]
> I'm sorry for that, I'm quite new to all this blog posting stuff.

It's alright, as I said, having a feed at all is a refreshing thing to see, and regardless, live and learn :)

> I've fixed \<pubDate> and placed \<guid> instead of \<link>. Does it work now?

It seems to for me (in particular with NetNewsWire). I'll let you know if anything else pops up. Cheers!
